#-------------------------------
# General Site Settings
title: Soyoung's
logo: logo.png # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Soyoung Cho
  image: code.gif
  say-hello: Hello, I’m <strong>Soyoung Cho</strong>
  bio: Current senior student at Kwangwoon University. My research interests include data mining, data analysis, data-based consulting and natural language processing.
  #bio: Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">music</a> & riding his bicycle.


#-------------------------------
# Contact links
facebook: https://www.facebook.com/soyoung.cho.543/
linkedin: https://www.linkedin.com/in/sophia-cho-4598bb1a5/
github: https://github.com/SoYoungCho/
#twitter: https://twitter.com/SoohwanKim6 # Add your Twitter handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://www.instagram.com/so_young_and_rich/?fbclid=IwAR1EIEpgSii5J5yTVZFSE-2mrqJ42_33m-_4GhaMxNwhvJH6LIWUhMpI9NI
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: Soyoung # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: so_young_and_rich # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
